#pragma once
#include "lvgl.h"


#define UI_PCT_PANEL_BG_COLOR			0x0A1F00
#define UI_PCT_PANEL_BORDER_COLOR		0x194C01
#define UI_PCT_PANEL_FG_COLOR			0x6DFF13
#define UI_PCT_PANEL_DIAG_BORDER_COLOR	0x621801
#define UI_PCT_PANEL_DIAG_BG_COLOR		0x300000
#define UI_PCT_PANEL_DIAG_FG_COLOR		0xFF0000

#define UI_PCT_BTN_BG_NORMAL_COLOR				0x0A1F00
#define UI_PCT_BTN_BG_ACTIVE_COLOR				0x164102
#define UI_PCT_BTN_FG_NORMAL_COLOR				0x6DFF13
#define UI_PCT_BTN_FG_DISALBE_COLOR				0x717171
#define KEYBOARD_0_STRING "B0\n"
#define KEYBOARD_1_STRING "B1\n"
#define KEYBOARD_2_STRING "B2\n"
#define KEYBOARD_3_STRING "B3\n"
#define KEYBOARD_4_STRING "B4\n"
#define KEYBOARD_5_STRING "B5\n"
#define KEYBOARD_6_STRING "B6\n"
#define KEYBOARD_7_STRING "B7\n"
#define KEYBOARD_8_STRING "B8\n"
#define KEYBOARD_9_STRING "B9\n"
#define KEYBOARD_CLEAR_STRING "B:\n"
#define KEYBOARD_BACKSPACE_STRING "B;\n"
#define KEYBOARD_POINT_STRING "B<\n"
#define KEYBOARD_PROG_STRING "B=\n"
#define KEYBOARD_ENTER_STRING "B>\n"
#define KEYBOARD_START_STRING "B?\n"
#define KEYBOARD_STOP_STRING "B@\n"
#define KEYBOARD_DIAG_STRING "BA\n"
#define KEYBOARD_COMM_STRING "BB\n"
#define KEYBOARD_HOME_STRING "BC\n"

enum
{
	UI_PCT_KEYBOARD_0,
	UI_PCT_KEYBOARD_1,
	UI_PCT_KEYBOARD_2,
	UI_PCT_KEYBOARD_3,
	UI_PCT_KEYBOARD_4,
	UI_PCT_KEYBOARD_5,
	UI_PCT_KEYBOARD_6,
	UI_PCT_KEYBOARD_7,
	UI_PCT_KEYBOARD_8,
	UI_PCT_KEYBOARD_9,
	UI_PCT_KEYBOARD_CLEAR,
	UI_PCT_KEYBOARD_BACKSPACE,
	UI_PCT_KEYBOARD_POINT,
	UI_PCT_KEYBOARD_PROG,
	UI_PCT_KEYBOARD_ENTER,
	UI_PCT_KEYBOARD_START,
	UI_PCT_KEYBOARD_STOP,
	UI_PCT_KEYBOARD_DIAG,
	UI_PCT_KEYBOARD_COMM,
	UI_PCT_KEYBOARD_HOME,
};



extern lv_obj_t* ui_pct_screen;

void ui_pct_screen_init(void);
void ui_pct_update_line(int index, const char* lineString);
void ui_pct_update_prog_mode(int value);